"""
Adapter layer for Indian Kanoon data.

Architecture:
    1. Load RAW data from kanoon_raw.json   (simulates Indian Kanoon API response)
    2. Load TAGS from vidhimur_tags.json    (our enrichment layer)
    3. Merge them into CaseRecord objects   (internal domain model)

When switching to the real API:
    - Replace _load_raw_docs() with an HTTP call
    - Tags will come from our database instead of a JSON file
"""

from __future__ import annotations

import json
import logging
from functools import lru_cache
from pathlib import Path

from pydantic import BaseModel, Field

from app.config import KANOON_RAW_FILE, VIDHIMUR_TAGS_FILE
from app.models.schemas import CaseRecord

logger = logging.getLogger(__name__)

# ---------------------------------------------------------------------------
# Indian Kanoon API Schema (raw, no enrichment)
# ---------------------------------------------------------------------------

class KanoonDocRef(BaseModel):
    """Reference to another doc (citeList / citedbyList item)."""
    tid: int
    title: str


class KanoonDoc(BaseModel):
    """Matches the shape of a single document from Indian Kanoon's API."""
    tid: int
    title: str
    headline: str | None = None
    docsource: str
    docsize: int
    publishdate: str                  # Format: DD-M-YYYY or D-M-YYYY
    numcites: int
    numcitedby: int
    catname: str
    citeList: list[KanoonDocRef] = Field(default_factory=list)
    citedbyList: list[KanoonDocRef] = Field(default_factory=list)


# ---------------------------------------------------------------------------
# VidhimurAI Enrichment Schema
# ---------------------------------------------------------------------------

class VidhimurTags(BaseModel):
    """Our enrichment data — generated by NLP/LLM after fetching from Kanoon."""
    keywords: list[str] = Field(default_factory=list)
    outcome: str = ""
    legal_issues: list[str] = Field(default_factory=list)
    statutes_referenced: list[str] = Field(default_factory=list)


# ---------------------------------------------------------------------------
# Loaders
# ---------------------------------------------------------------------------

@lru_cache(maxsize=1)
def _load_raw_docs() -> list[KanoonDoc]:
    """Load raw Indian Kanoon documents (simulated from local JSON)."""
    if not KANOON_RAW_FILE.exists():
        raise FileNotFoundError(f"Raw Kanoon dataset not found at {KANOON_RAW_FILE}")
    with open(KANOON_RAW_FILE, encoding="utf-8") as f:
        return [KanoonDoc(**doc) for doc in json.load(f)]


@lru_cache(maxsize=1)
def _load_tags() -> dict[str, VidhimurTags]:
    """Load enrichment tags keyed by tid (as string)."""
    if not VIDHIMUR_TAGS_FILE.exists():
        return {}  # No tags available — still functional, just less enriched
    with open(VIDHIMUR_TAGS_FILE, encoding="utf-8") as f:
        raw = json.load(f)
    return {tid: VidhimurTags(**data) for tid, data in raw.items()}


# ---------------------------------------------------------------------------
# Merge Logic (the core adapter)
# ---------------------------------------------------------------------------

def _merge(doc: KanoonDoc, tags: VidhimurTags | None) -> CaseRecord:
    """
    Merge raw Kanoon data + enrichment tags into a single CaseRecord.

    - Raw data provides:  tid, title, court, date, citations
    - Tags provide:       keywords, legal issues, statutes, outcome
    - If no tags exist:   CaseRecord still works, just with empty enrichment
    """

    # Parse year from publishdate (DD-M-YYYY)
    try:
        year = int(doc.publishdate.split("-")[-1])
    except (IndexError, ValueError):
        year = 0

    # Build summary from headline + outcome
    summary = doc.headline or ""
    if tags and tags.outcome:
        summary += f" Outcome: {tags.outcome}"

    return CaseRecord(
        id=f"KANOON-{doc.tid}",
        kanoon_tid=doc.tid,
        case_name=doc.title,
        court=doc.docsource,
        year=year,
        citation_count=doc.numcitedby,
        summary=summary,
        # Enrichment (empty if no tags)
        keywords=tags.keywords if tags else [],
        outcome=tags.outcome if tags else "",
        legal_issues=tags.legal_issues if tags else [],
        statutes_referenced=tags.statutes_referenced if tags else [],
        precedents_cited=[c.title for c in doc.citeList],
    )


# ---------------------------------------------------------------------------
# Failure Strategy — Last successful result fallback
# ---------------------------------------------------------------------------

_last_good_results: list[CaseRecord] = []


# ---------------------------------------------------------------------------
# Public API
# ---------------------------------------------------------------------------

def get_all_cases() -> list[CaseRecord]:
    """
    Load raw Kanoon docs + enrichment tags, merge them, return CaseRecords.

    Failure Strategy:
        If loading fails, fall back to the last successful result.
        This ensures the system never fully breaks.
    """
    global _last_good_results

    try:
        raw_docs = _load_raw_docs()
        tags_map = _load_tags()

        results = [
            _merge(doc, tags_map.get(str(doc.tid)))
            for doc in raw_docs
        ]

        _last_good_results = results  # Cache for fallback
        return results

    except Exception as e:
        logger.error(f"Failed to load Kanoon data: {e}")

        if _last_good_results:
            logger.warning("Falling back to last successful data load.")
            return _last_good_results

        logger.critical("No fallback data available. Returning empty list.")
        return []
